source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'RxRealm_Example' do
  platform :ios, '8.0'
  pod 'RxRealm', :path => '../'
  pod 'RxSwift',    '~> 4'
  pod 'RxCocoa',    '~> 4'
  pod 'RealmSwift', '~> 3'
end

target 'RxRealm_Tests' do
  platform :ios, '8.0'
  pod 'RxSwift',    '~> 4'
  pod 'RxCocoa',    '~> 4'
  pod 'RxTest',    '~> 4'
  pod 'RealmSwift', '~> 3'
  pod 'RxRealm', :path => '../'
end
